export const ADD_MOVIES = "ADD_MOVIES";

export const CREATE_MOVIE = "CREATE_MOVIE";

export const EDIT_MOVIE = "EDIT_MOVIE";

export const DELETE_MOVIE = "DELETE_MOVIE";

export const ADD_MOVIE = "ADD_MOVIE";

export const CREATE_COMMENT = "CREATE_COMMENT";

export const EDIT_COMMENT = "EDIT_COMMENT";

export const DELETE_COMMENT = "DELETE_COMMENT";

export const SET_FAVORITE_MOVIE = "SET_FAVORITE_MOVIE";

export const SET_PERSONAL_RATING = "SET_PERSONAL_RATING";

export const SET_AVARAGE_RATING = "SET_AVARAGE_RATING";
