export const ADD_MOVIE = "ADD_MOVIE";

export const CREATE_COMMENT = "CREATE_COMMENT";

export const EDIT_COMMENT = "EDIT_COMMENT";

export const DELETE_COMMENT = "DELETE_COMMENT";

export const SET_FAVORITE_MOVIE = "SET_FAVORITE_MOVIE";

export const SET_PERSONAL_RATING = "SET_PERSONAL_RATING";

export const SET_AVARAGE_RATING = "SET_AVARAGE_RATING";

export const SEARCH_CHANGE = "SEARCH_CHANGE";

export const SELECT_CHANGE = "SELECT_CHANGE";

export const SORT_CHANGE = "SORT_CHANGE";

export const CATEGORY_CHANGE = "CATEGORY_CHANGE";

export const TAG_CHANGE = "TAG_CHANGE";

export const RESET_CHANGE = "RESET_CHANGE";

export const ITEM_PER_PAGE_CHANGE = "ITEM_PER_PAGE_CHANGE";

export const CURRENT_PAGE_CHANGE = "CURRENT_PAGE_CHANGE";

export const TOP_RATED_CHANGE = "TOP_RATED_CHANGE";
